# Generated by Django 3.0.8 on 2020-07-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_manufacturer',
            new_name='manufacturer',
        ),
    ]
