# Generated by Django 3.0.8 on 2020-07-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20200706_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative')], default='POS', max_length=3),
        ),
    ]
