// Stock Actions
export const ADD_STOCK = 'ADD_STOCK'; //PUT
export const SUBTRACT_STOCK = 'SUBTRACT_STOCK'; //PUT

// Products Actions
export const GET_PRODUCTS = 'GET_PRODUCTS'; //GET
export const ADD_PRODUCT = 'ADD_PRODUCT'; //POST
export const DELETE_PRODUCT = 'DELETE_STOCK'; //DELETE

// Manufacturers Actions
export const GET_MANUFACTURERS = 'GET_MANUFACTURERS'; //GET
export const ADD_MANUFACTURERS = 'ADD_MANUFACTURERS'; //POST
export const DELETE_MANUFACTURERS = 'DELETE_MANUFACTURERS'; //DELETE

// Suppliers Actions
export const GET_SUPPLIERS = 'GET_SUPPLIERS'; //GET
export const ADD_SUPPLIERS = 'ADD_SUPPLIERS'; //POST
export const DELETE_SUPPLIERS = 'DELETE_SUPPLIERS'; //DELETE

//Transactions Actions
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS'; //GET
export const POSITIVE_TRANSACTION = 'POSITIVE_TRANSACTION'; //PUT
export const NEGATIVE_TRANSACTION = 'NEGATIVE_TRANSACTION'; //PUT
